name: botika_va
description: A new Flutter plugin of botika Virtual Avatar, providing component to send text and then receive response text and video 
version: 0.1.6
homepage: https://github.com/mobiledevbotika/botika_va
repository: https://github.com/mobiledevbotika/botika_va
issue_tracker: https://github.com/mobiledevbotika/botika_va/issues

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_client_sse: ^2.0.0
  http: ^0.13.5
  remove_emoji: ^0.0.10

client_sse:
    git:
      url: https://github.com/pratikbaid3/flutter_client_sse
      path:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
